<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $data = [
      ["nombre" => capitalizarPalabra('AHUACHAPAN'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('APANECA'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('ATIQUIZAYA'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('CONCEPCIÓN DE ATACO'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('EL REFUGIO'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('GUAYMANGO'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('JUJUTLA'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('SAN FRANCISCO MENENDEZ'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('SAN LORENZO'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('SAN PEDRO PUXTLA'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('TACUBA'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('TURIN'), "id_departamento" => 1],
      ["nombre" => capitalizarPalabra('CANDELARIA DE LA FRONTERA'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('COATEPEQUE'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('CHALCHUAPA'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('EL CONGO'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('EL PORVENIR'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('MASAHUAT'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('METAPAN'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('SAN ANTONIO PAJONAL'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('SAN SEBASTIAN SALITRILLO'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('SANTA ANA'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('SANTA ROSA GUACHIPILIN'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('SANTIAGO DE LA FRONTERA'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('TEXISTEPEQUE'), "id_departamento" => 2],
      ["nombre" => capitalizarPalabra('ACAJUTLA'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('ARMENIA'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('CALUCO'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('CUISNAHUAT'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SANTA ISABEL ISHUATÁN'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('IZALCO'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('JUAYUA'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('NAHUIZALCO'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('NAHULINGO'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SALCOATITAN'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SAN ANTONIO DEL MONTE'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SAN JULIAN'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SANTA CATARINA MASAHUAT'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SANTO DOMINGO DE GUZMAN'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SONSONATE'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('SONZACATE'), "id_departamento" => 3],
      ["nombre" => capitalizarPalabra('AGUA CALIENTE'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('ARCATAO'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('AZACUALPA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('CITALA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('COMALAPA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('CONCEPCION QUEZALTEPEQUE'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('CHALATENANGO'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('DULCE NOMBRE DE MARÍA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('EL CARRIZAL'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('EL PARAISO'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('LA LAGUNA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('LA PALMA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('LA REINA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('LAS VUELTAS'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('NOMBRE DE JESÚS'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('NUEVA CONCEPCION'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('NUEVA TRINIDAD'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('OJOS DE AGUA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('POTONICO'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN ANTONIO DE LA CRUZ'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN ANTONIO LOS RANCHOS'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN FERNANDO'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN FRANCISCO LEMPA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN FRANCISCO MORAZÁN'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN IGNACIO'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN ISIDRO LABRADOR'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('CANCASQUE'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('LAS FLORES'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN LUIS DEL CARMEN'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN MIGUEL DE MERCEDES'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SAN RAFAEL'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('SANTA RITA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('TEJUTLA'), "id_departamento" => 4],
      ["nombre" => capitalizarPalabra('ANTIGUO CUSCATLAN'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('CIUDAD ARCE'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('COLON'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('COMASAGUA'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('CHILTIUPAN'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('HUIZUCAR'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('JAYAQUE'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('JICALAPA'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('LA LIBERTAD'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('NUEVO CUSCATLAN'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('SANTA TECLA'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('QUEZALTEPEQUE'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('SACACOYO'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('SAN JOSE VILLANUEVA'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('SAN JUAN OPICO'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('SAN MATÍAS'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('SAN PABLO TACACHICO'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('TAMANIQUE'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('TALNIQUE'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('TEOTEPEQUE'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('TEPECOYO'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('ZARAGOZA'), "id_departamento" => 5],
      ["nombre" => capitalizarPalabra('AGUILARES'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('APOPA'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('AYUTUXTEPEQUE'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('CUSCATANCINGO'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('EL PAISNAL'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('GUAZAPA'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('ILOPANGO'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('MEJICANOS'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('NEJAPA'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('PANCHIMALCO'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('ROSARIO DE MORA'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('SAN MARCOS'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('SAN MARTIN'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('SAN SALVADOR'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('SANTIAGO TEXACUANGOS'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('SANTO TOMAS'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('SOYAPANGO'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('TONACATEPEQUE'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('CIUDAD DELGADO'), "id_departamento" => 6],
      ["nombre" => capitalizarPalabra('CANDELARIA'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('COJUTEPEQUE'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('EL CARMEN'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('EL ROSARIO'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('MONTE SAN JUAN'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('ORATORIO DE CONCEPCIÓN'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SAN BARTOLOME PERULAPIA'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SAN CRISTÓBAL'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SAN JOSE GUAYABAL'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SAN PEDRO PERULAPAN'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SAN RAFAEL CEDROS'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SAN RAMÓN'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SANTA CRUZ ANALQUITO'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SANTA CRUZ MICHAPA'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('SUCHITOTO'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('TENANCINGO'), "id_departamento" => 7],
      ["nombre" => capitalizarPalabra('CUYULTITAN'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('EL ROSARIO'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('JERUSALÉN'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('MERCEDES LA CEIBA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('OLOCUILTA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('PARAÍSO DE OSORIO'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN ANTONIO MASAHUAT'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN EMIGDIO'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN FRANCISCO CHINAMECA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN JUAN NONUALCO'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN JUAN TALPA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN JUAN TEPEZONTES'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN LUIS TALPA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN MIGUEL TEPEZONTES'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN PEDRO MASAHUAT'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN PEDRO NONUALCO'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN RAFAEL OBRAJUELO'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SANTA MARÍA OSTUMA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SANTIAGO NONUALCO'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('TAPALHUACA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('ZACATECOLUCA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('SAN LUIS LA HERRADURA'), "id_departamento" => 8],
      ["nombre" => capitalizarPalabra('CINQUERA'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('GUACOTECTI'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('ILOBASCO'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('JUTIAPA'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('SAN ISIDRO'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('SENSUNTEPEQUE'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('TEJUTEPEQUE'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('VICTORIA'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('DOLORES'), "id_departamento" => 9],
      ["nombre" => capitalizarPalabra('APASTEPEQUE'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('GUADALUPE'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SAN CAYETANO ISTEPEQUE'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SANTA CLARA'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SANTO DOMINGO'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SAN ESTEBAN CATARINA'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SAN ILDEFONSO'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SAN LORENZO'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SAN SEBASTIAN'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('SAN VICENTE'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('TECOLUCA'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('TEPETITÁN'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('VERAPAZ'), "id_departamento" => 10],
      ["nombre" => capitalizarPalabra('ALEGRIA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('BERLIN'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('CALIFORNIA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('CONCEPCION BATRES'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('EL TRIUNFO'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('EREGUAYQUIN'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('ESTANZUELAS'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('JIQUILISCO'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('JUCUAPA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('JUCUARÁN'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('MERCEDES UMAÑA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('NUEVA GRANADA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('OZATLAN'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('PUERTO EL TRIUNFO'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('SAN AGUSTIN'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('SAN BUENA VENTURA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('SAN DIONISIO'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('SANTA ELENA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('SAN FRANCISCO JAVIER'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('SANTA MARIA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('SANTIAGO DE MARIA'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('TECAPAN'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('USULUTAN'), "id_departamento" => 11],
      ["nombre" => capitalizarPalabra('CAROLINA'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('CIUDAD BARRIOS'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('COMACARAN'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('CHAPELTIQUE'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('CHINAMECA'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('CHIRILAGUA'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('EL TRANSITO'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('LOLOTIQUE'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('MONCAGUA'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('NUEVA GUADALUPE'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('NUEVO EDEN DE SAN JUAN'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('QUELEPA'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('SAN ANTONIO'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('SAN GERARDO'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('SAN JORGE'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('SAN LUIS DE LA REINA'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('SAN MIGUEL'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('SAN RAFAEL ORIENTE'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('SESORI'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('ULUAZAPA'), "id_departamento" => 12],
      ["nombre" => capitalizarPalabra('ARAMBALA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('CACAOPERA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('CORINTO'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('CHILANGA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('DELICIAS DE CONCEPCIÓN'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('EL DIVISADERO'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('EL ROSARIO'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('GUALOCOCTI'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('GUATAJIAGUA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('JOATECA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('JOCOAITIQUE'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('JOCORO'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('LOLOTIQUILLO'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('MEANGUERA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('OSCICALA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('PERQUIN'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('SAN CARLOS'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('SAN FERNANDO'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('SAN FRANCISCO GOTERA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('SAN ISIDRO'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('SAN SIMON'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('SENSEMBRA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('SOCIEDAD'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('TOROLA'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('YAMABAL'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('YOLOAIQUIN'), "id_departamento" => 13],
      ["nombre" => capitalizarPalabra('ANAMOROS'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('BOLÍVAR'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('CONCEPCION DE ORIENTE'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('CONCHAGUA'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('EL CARMEN'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('EL SAUCE'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('INTIPUCÁ'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('LA UNION'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('LISLIQUE'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('MEANGUERA DEL GOLFO'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('NUEVA ESPARTA'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('PASAQUINA'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('POLOROS'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('SAN ALEJO'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('SAN JOSÉ'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('SANTA ROSA DE LIMA'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('YAYANTIQUE'), "id_departamento" => 14],
      ["nombre" => capitalizarPalabra('YUCUAIQUÍN'), "id_departamento" => 14],
    ];

    DB::table('municipios')->insert($data);
  }
}
